apiVersion: v1
kind: Service
metadata:
  name: recommender-api
  namespace: cinerankml
  labels:
    app.kubernetes.io/name: recommender-api
    app.kubernetes.io/part-of: cinerankml
spec:
  selector:
    app.kubernetes.io/name: recommender-api
  ports:
    - name: http
      port: 8090
      targetPort: http
