apiVersion: v1
kind: Service
metadata:
  name: kafka
  namespace: cinerankml
  labels:
    app.kubernetes.io/name: kafka
    app.kubernetes.io/part-of: cinerankml
spec:
  clusterIP: None
  selector:
    app.kubernetes.io/name: kafka
  ports:
    - name: kafka
      port: 9092
      targetPort: kafka
    - name: controller
      port: 9093
      targetPort: controller
