apiVersion: v1
kind: Service
metadata:
  name: ratings-consumer
  namespace: cinerankml
  labels:
    app.kubernetes.io/name: ratings-consumer
    app.kubernetes.io/part-of: cinerankml
spec:
  selector:
    app.kubernetes.io/name: ratings-consumer
  ports:
    - name: metrics
      port: 9102
      targetPort: metrics
