apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

# CI updates these newTags to the CineRankML git SHA after each image push.
images:
- name: ghcr.io/tmir00/cinerankml-embedder-api
  newName: ghcr.io/tmir00/cinerankml-embedder-api
  newTag: 67453923f0072c2778c383ccc7ff8bc8c4241e48
- name: ghcr.io/tmir00/cinerankml-frontend
  newName: ghcr.io/tmir00/cinerankml-frontend
  newTag: 67453923f0072c2778c383ccc7ff8bc8c4241e48
- name: ghcr.io/tmir00/cinerankml-migrate
  newName: ghcr.io/tmir00/cinerankml-migrate
  newTag: 67453923f0072c2778c383ccc7ff8bc8c4241e48
- name: ghcr.io/tmir00/cinerankml-ratings-consumer
  newName: ghcr.io/tmir00/cinerankml-ratings-consumer
  newTag: 67453923f0072c2778c383ccc7ff8bc8c4241e48
- name: ghcr.io/tmir00/cinerankml-recommender-api
  newName: ghcr.io/tmir00/cinerankml-recommender-api
  newTag: 67453923f0072c2778c383ccc7ff8bc8c4241e48

patches:
- path: patches/resources.yaml
- path: patches/ingress-hosts.yaml
