apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

# CI updates these newTags to the CineRankML git SHA after each image push.
images:
  - name: ghcr.io/tmir00/cinerankml-migrate
    newTag: latest
  - name: ghcr.io/tmir00/cinerankml-ratings-consumer
    newTag: latest
  - name: ghcr.io/tmir00/cinerankml-embedder-api
    newTag: latest
  - name: ghcr.io/tmir00/cinerankml-recommender-api
    newTag: latest
  - name: ghcr.io/tmir00/cinerankml-frontend
    newTag: latest

patches:
  - path: patches/resources.yaml
  - path: patches/ingress-hosts.yaml
