apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

# CI updates these newTags to the CineRankML git SHA after each image push.
images:
- name: ghcr.io/tmir00/cinerankml-embedder-api
  newName: ghcr.io/tmir00/cinerankml-embedder-api
  newTag: 521ee4d5e4182fa1c223e079ee352faecead96cc
- name: ghcr.io/tmir00/cinerankml-frontend
  newName: ghcr.io/tmir00/cinerankml-frontend
  newTag: 521ee4d5e4182fa1c223e079ee352faecead96cc
- name: ghcr.io/tmir00/cinerankml-migrate
  newName: ghcr.io/tmir00/cinerankml-migrate
  newTag: 521ee4d5e4182fa1c223e079ee352faecead96cc
- name: ghcr.io/tmir00/cinerankml-ratings-consumer
  newName: ghcr.io/tmir00/cinerankml-ratings-consumer
  newTag: 521ee4d5e4182fa1c223e079ee352faecead96cc
- name: ghcr.io/tmir00/cinerankml-recommender-api
  newName: ghcr.io/tmir00/cinerankml-recommender-api
  newTag: 521ee4d5e4182fa1c223e079ee352faecead96cc

patches:
- path: patches/resources.yaml
- path: patches/ingress-hosts.yaml
