apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mlflow-artifacts
  namespace: cinerankml
  labels:
    app.kubernetes.io/name: mlflow
    app.kubernetes.io/part-of: cinerankml
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
