apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cinerankml

resources:
  - namespace.yaml
  - config/configmap.yaml
  - config/secret.yaml
  - postgres/statefulset.yaml
  - postgres/service.yaml
  - kafka/statefulset.yaml
  - kafka/service.yaml
  - opensearch/statefulset.yaml
  - opensearch/service.yaml
  - minio/statefulset.yaml
  - minio/service.yaml
  - minio/init-job.yaml
  - migrate/job.yaml
  - ratings-consumer/deployment.yaml
  - embedder-api/deployment.yaml
  - embedder-api/service.yaml
  - recommender-api/deployment.yaml
  - recommender-api/service.yaml
  - frontend/deployment.yaml
  - frontend/service.yaml
  - ingress/ingress.yaml

labels:
  - pairs:
      app.kubernetes.io/part-of: cinerankml
    includeSelectors: false
