apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: cinerankml
  labels:
    app.kubernetes.io/name: postgres
    app.kubernetes.io/part-of: cinerankml
spec:
  clusterIP: None
  selector:
    app.kubernetes.io/name: postgres
  ports:
    - name: postgres
      port: 5432
      targetPort: postgres
